version: "3"
services:
  # redis:
  #   container_name: pgsites-redis
  #   image: redis:alpine
  #   restart: unless-stopped
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  #   env_file:
  #     - .env.local
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - pgsites-network
  main:
    container_name: main
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    ports:
      - "5005:5005"
      - "3000:3000"
    volumes:
      - ./:/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - pgsites-network

  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env.local
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/data/db
    networks:
      - pgsites-network


volumes:
  postgres-data:

networks:
  pgsites-network:
    driver: bridge