version: "3"
services:
  # redis:
  #   container_name: pgsites-redis
  #   image: redis:alpine
  #   restart: unless-stopped
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  #   env_file:
  #     - .env.local
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - pgsites-network
  pgsites:
    container_name: pgsites
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    ports:
      - "5005:5005"
      - "3000:3000"
    volumes:
      - ./:/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - pgsites-network
#   mongodb:
#     image: mongo:latest
#     container_name: pgsites-mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb-data:/data/db
#     networks:
#       - pgsites-network


# volumes:
#   mongodb-data:

networks:
  pgsites-network:
    driver: bridge