"use client" 
// import type { Metadata } from "next";
import localFont from "next/font/local";
import LoginButtons from "./components/LoginButtons";

import { SessionProvider } from "next-auth/react"

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="grid grid-cols-3 grid-rows-3 gap-4">
        <div className="col-start-2 row-start-1 items-center justify-items-center"> PARAGLIDING SITES APP</div>
        
       
        <SessionProvider>
         <div className="col-start-3"> 
          <LoginButtons />
        </div>
        <div className="col-start-2 row-start-2"> 
          {children} 
        </div>

        </SessionProvider>
      </div>
      </body>
    </html>
  );
}