import type { Metadata } from "next";
import localFont from "next/font/local";
import Button from '@mui/material/Button';
import Link from 'next/link'

import { useSession, signOut } from "next-auth/react"

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { data: session } = useSession()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<div className="grid grid-cols-2 grid-rows-3 gap-4">
      <div className="col-start-2 row-start-1"> PARAGLIDING SITES APP</div>
        <div className="col-start-3"> 

        {session && (
          <>
            Signed in as {session.user!.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}

        {session! && (
          <>  
            <Link href="\login"> <Button variant="outlined">Login</Button></Link><Button variant="outlined">Register</Button>
          </>
        )}    
        </div>

        {children}

        </div>
      </body>
    </html>
  );
}